### ISSUE TITLE
Can't see expanded links for course in s23

### ISSUE THREAD

**Issue by m-ichelleliu** [joshuamotoaki/tiger-junction#20]
<img width="1440" alt="image" src="https://github.com/joshuamotoaki/tiger-junction/assets/91390445/8fab7c14-1498-4a4f-95c5-5f63e0ffb0ad">

tigersnatch link is the only one clickable and its broken

**Comment by joshuamotoaki** [comment]
TigerSnatch link issue fixed in #21 (there is no valid link to TigerSnatch for previous semesters, so the button to do so in previous terms is just removed). This is actually the behavior of ReCal, so good catch. As for only one being visible, you can scroll through the saved course area to find the other parts. When there's a search result, right now I'm using an easy hack where the search result area appears at a fixed point, and so even if the search results don't fill the page, a part of the saved courses still becomes a scroll area. This will be updated in a future patch, but for now it's functional enough.
